model_name: "dimenet++"

emb_size: 128
out_emb_size: 256
int_emb_size: 64
basis_emb_size: 8
num_blocks: 4

num_spherical: 7
num_radial: 6
output_init: 'GlorotOrthogonal'  # 'zeros' for mu, homo, lumo, and zpve; 'GlorotOrthogonal' for alpha, R2, U0, U, H, G, and Cv

extensive: False
cutoff: 5.0
envelope_exponent: 5

num_before_skip: 1
num_after_skip: 2
num_dense_output: 3

dataset: "data/Decomposition_energy_nan.npz"

batch_size: 32
comment: "final"
target: 'Stable'  
#['Thermodynamic_stability_level','Phonon_dynamic_stability','Stiffness_dynamic_stability','Work_function','Vmax','Vmin','Exfoliation_energy','Exfoliation_energy_jarvis','Stable','Meta_stable','Dynamical_stable','Heat_of_formation','Decomposition_energy_nan', 'Formation_energy_peratom_nan', 'Formation_energy_peratom']

data_aug: False
